title: "pixelart by paz"

theme: minima

collections:
  - scenes

author:
  name: Alexander Paz
  short_name: '@alexjpaz'
  email: "alex.j.paz@gmail.com"
  website: "https://alexjpaz.com"

github_url: "https://github.com/alexjpaz/pixelart"
