title: "pixelart by paz"

theme: minima

collections:
  - scenes

author:
  name: Alexander Paz
  email: "alex.j.paz@gmail.com"
  website: "https://alexjpaz.com"

header_pages:
  - about.md
  - gallery/index.md
